//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppClient.ITPIService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost:8888/Services/ITPI/Service1.asmx", ConfigurationName="ITPIService.Service1Soap")]
    public interface Service1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8888/Services/ITPI/Service1.asmx/Message", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Message(string request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8888/Services/ITPI/Service1.asmx/GetPrInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetPrInfo(ConsoleAppClient.ITPIService.PrEproc domain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8888/Services/ITPI/Service1.asmx/GetPrLineInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetPrLineInfo(ConsoleAppClient.ITPIService.PrLineEproc domain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8888/Services/ITPI/Service1.asmx/GetPrSubtaskInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetPrSubtaskInfo(ConsoleAppClient.ITPIService.PrSubTask domain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8888/Services/ITPI/Service1.asmx/InsertDepartment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string InsertDepartment(ConsoleAppClient.ITPIService.Department departemen);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8888/Services/ITPI/Service1.asmx/InsertEmployee", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string InsertEmployee(ConsoleAppClient.ITPIService.Employee employee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8888/Services/ITPI/Service1.asmx/InsertVendor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string InsertVendor(ConsoleAppClient.ITPIService.Vendor vendor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8888/Services/ITPI/Service1.asmx/InsertCity", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string InsertCity(ConsoleAppClient.ITPIService.City city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8888/Services/ITPI/Service1.asmx/InsertProvince", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string InsertProvince(ConsoleAppClient.ITPIService.Province prov);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8888/Services/ITPI/Service1.asmx/InsertPR", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string InsertPR(ConsoleAppClient.ITPIService.PurchaseRequisition pr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8888/Services/ITPI/Service1.asmx/InsertPrLine", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string InsertPrLine(ConsoleAppClient.ITPIService.PurchaseRequisitionLine prl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8888/Services/ITPI/Service1.asmx/InsertPrDocument", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string InsertPrDocument(ConsoleAppClient.ITPIService.PrDocument prDoc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8888/Services/ITPI/Service1.asmx/Get", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Get(ConsoleAppClient.ITPIService.BaseModel model);
        
        // CODEGEN: Parameter 'criteria' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8888/Services/ITPI/Service1.asmx/Find", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ConsoleAppClient.ITPIService.FindResponse Find(ConsoleAppClient.ITPIService.FindRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8888/Services/ITPI/Service1.asmx/IsPrApproved", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool IsPrApproved(string prId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8888/Services/ITPI/Service1.asmx/CreatePO", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CreatePO(string jsonParameters);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost:8888/Services/ITPI/Service1.asmx")]
    public partial class PrEproc : PurchaseRequisition {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PrEproc))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost:8888/Services/ITPI/Service1.asmx")]
    public partial class PurchaseRequisition : BaseModel {
        
        private int idField;
        
        private string codeField;
        
        private string nameField;
        
        private bool confirmedField;
        
        private bool createdField;
        
        private string documentUrlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool Confirmed {
            get {
                return this.confirmedField;
            }
            set {
                this.confirmedField = value;
                this.RaisePropertyChanged("Confirmed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool Created {
            get {
                return this.createdField;
            }
            set {
                this.createdField = value;
                this.RaisePropertyChanged("Created");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string DocumentUrl {
            get {
                return this.documentUrlField;
            }
            set {
                this.documentUrlField = value;
                this.RaisePropertyChanged("DocumentUrl");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PrDocument))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Province))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(City))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Vendor))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Roles))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Employee))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Department))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PrSubTask))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PurchaseRequisitionLine))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PrLineEproc))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PurchaseRequisition))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PrEproc))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost:8888/Services/ITPI/Service1.asmx")]
    public partial class BaseModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost:8888/Services/ITPI/Service1.asmx")]
    public partial class PrDocument : BaseModel {
        
        private int idField;
        
        private string codeField;
        
        private string urlDocumentField;
        
        private PurchaseRequisition prField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string UrlDocument {
            get {
                return this.urlDocumentField;
            }
            set {
                this.urlDocumentField = value;
                this.RaisePropertyChanged("UrlDocument");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public PurchaseRequisition PR {
            get {
                return this.prField;
            }
            set {
                this.prField = value;
                this.RaisePropertyChanged("PR");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost:8888/Services/ITPI/Service1.asmx")]
    public partial class Province : BaseModel {
        
        private int idField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost:8888/Services/ITPI/Service1.asmx")]
    public partial class City : BaseModel {
        
        private int idField;
        
        private Province provinceField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Province Province {
            get {
                return this.provinceField;
            }
            set {
                this.provinceField = value;
                this.RaisePropertyChanged("Province");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost:8888/Services/ITPI/Service1.asmx")]
    public partial class Vendor : BaseModel {
        
        private int idField;
        
        private string nameField;
        
        private string nPWPField;
        
        private string addressField;
        
        private string phoneField;
        
        private string faxField;
        
        private string emailField;
        
        private string websiteField;
        
        private string postalCodeField;
        
        private City cityField;
        
        private Province provinceField;
        
        private string bankAccountNameField;
        
        private string bankAccountNumberField;
        
        private string axIdField;
        
        private bool onHoldField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string NPWP {
            get {
                return this.nPWPField;
            }
            set {
                this.nPWPField = value;
                this.RaisePropertyChanged("NPWP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("Address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
                this.RaisePropertyChanged("Phone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Fax {
            get {
                return this.faxField;
            }
            set {
                this.faxField = value;
                this.RaisePropertyChanged("Fax");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Website {
            get {
                return this.websiteField;
            }
            set {
                this.websiteField = value;
                this.RaisePropertyChanged("Website");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
                this.RaisePropertyChanged("PostalCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public City City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public Province Province {
            get {
                return this.provinceField;
            }
            set {
                this.provinceField = value;
                this.RaisePropertyChanged("Province");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string BankAccountName {
            get {
                return this.bankAccountNameField;
            }
            set {
                this.bankAccountNameField = value;
                this.RaisePropertyChanged("BankAccountName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string BankAccountNumber {
            get {
                return this.bankAccountNumberField;
            }
            set {
                this.bankAccountNumberField = value;
                this.RaisePropertyChanged("BankAccountNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string AxId {
            get {
                return this.axIdField;
            }
            set {
                this.axIdField = value;
                this.RaisePropertyChanged("AxId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public bool OnHold {
            get {
                return this.onHoldField;
            }
            set {
                this.onHoldField = value;
                this.RaisePropertyChanged("OnHold");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost:8888/Services/ITPI/Service1.asmx")]
    public partial class Roles : BaseModel {
        
        private int idField;
        
        private string authorityField;
        
        private bool activeField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Authority {
            get {
                return this.authorityField;
            }
            set {
                this.authorityField = value;
                this.RaisePropertyChanged("Authority");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
                this.RaisePropertyChanged("Active");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost:8888/Services/ITPI/Service1.asmx")]
    public partial class Employee : BaseModel {
        
        private int idField;
        
        private string nameField;
        
        private string nIKField;
        
        private string emailField;
        
        private string phoneField;
        
        private string dateCreatedField;
        
        private int createdByField;
        
        private string lastUpdateField;
        
        private int updatedByField;
        
        private string usernameField;
        
        private string passwordField;
        
        private bool activeField;
        
        private string positionField;
        
        private string sectionField;
        
        private Department departmentField;
        
        private Roles roleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string NIK {
            get {
                return this.nIKField;
            }
            set {
                this.nIKField = value;
                this.RaisePropertyChanged("NIK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
                this.RaisePropertyChanged("Phone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string DateCreated {
            get {
                return this.dateCreatedField;
            }
            set {
                this.dateCreatedField = value;
                this.RaisePropertyChanged("DateCreated");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int CreatedBy {
            get {
                return this.createdByField;
            }
            set {
                this.createdByField = value;
                this.RaisePropertyChanged("CreatedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string LastUpdate {
            get {
                return this.lastUpdateField;
            }
            set {
                this.lastUpdateField = value;
                this.RaisePropertyChanged("LastUpdate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int UpdatedBy {
            get {
                return this.updatedByField;
            }
            set {
                this.updatedByField = value;
                this.RaisePropertyChanged("UpdatedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public bool Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
                this.RaisePropertyChanged("Active");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
                this.RaisePropertyChanged("Position");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Section {
            get {
                return this.sectionField;
            }
            set {
                this.sectionField = value;
                this.RaisePropertyChanged("Section");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public Department Department {
            get {
                return this.departmentField;
            }
            set {
                this.departmentField = value;
                this.RaisePropertyChanged("Department");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public Roles Role {
            get {
                return this.roleField;
            }
            set {
                this.roleField = value;
                this.RaisePropertyChanged("Role");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost:8888/Services/ITPI/Service1.asmx")]
    public partial class Department : BaseModel {
        
        private int idField;
        
        private string nameField;
        
        private bool activeField;
        
        private string descriptionField;
        
        private string axIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
                this.RaisePropertyChanged("Active");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string AxId {
            get {
                return this.axIdField;
            }
            set {
                this.axIdField = value;
                this.RaisePropertyChanged("AxId");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost:8888/Services/ITPI/Service1.asmx")]
    public partial class PrSubTask : BaseModel {
        
        private int idField;
        
        private string nameField;
        
        private string poNumberField;
        
        private int revisionField;
        
        private PrEproc prField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PoNumber {
            get {
                return this.poNumberField;
            }
            set {
                this.poNumberField = value;
                this.RaisePropertyChanged("PoNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Revision {
            get {
                return this.revisionField;
            }
            set {
                this.revisionField = value;
                this.RaisePropertyChanged("Revision");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public PrEproc PR {
            get {
                return this.prField;
            }
            set {
                this.prField = value;
                this.RaisePropertyChanged("PR");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PrLineEproc))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost:8888/Services/ITPI/Service1.asmx")]
    public partial class PurchaseRequisitionLine : BaseModel {
        
        private int idField;
        
        private int numberField;
        
        private string descriptionField;
        
        private int quantityField;
        
        private string unitField;
        
        private double unitCostField;
        
        private double lineCostField;
        
        private double taxField;
        
        private bool activeField;
        
        private PurchaseRequisition prField;
        
        private int lineNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("Number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
                this.RaisePropertyChanged("Quantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
                this.RaisePropertyChanged("Unit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public double UnitCost {
            get {
                return this.unitCostField;
            }
            set {
                this.unitCostField = value;
                this.RaisePropertyChanged("UnitCost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public double LineCost {
            get {
                return this.lineCostField;
            }
            set {
                this.lineCostField = value;
                this.RaisePropertyChanged("LineCost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public double Tax {
            get {
                return this.taxField;
            }
            set {
                this.taxField = value;
                this.RaisePropertyChanged("Tax");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public bool Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
                this.RaisePropertyChanged("Active");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public PurchaseRequisition PR {
            get {
                return this.prField;
            }
            set {
                this.prField = value;
                this.RaisePropertyChanged("PR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int LineNumber {
            get {
                return this.lineNumberField;
            }
            set {
                this.lineNumberField = value;
                this.RaisePropertyChanged("LineNumber");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost:8888/Services/ITPI/Service1.asmx")]
    public partial class PrLineEproc : PurchaseRequisitionLine {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Find", WrapperNamespace="http://localhost:8888/Services/ITPI/Service1.asmx", IsWrapped=true)]
    public partial class FindRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost:8888/Services/ITPI/Service1.asmx", Order=0)]
        public ConsoleAppClient.ITPIService.BaseModel model;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost:8888/Services/ITPI/Service1.asmx", Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] criteria;
        
        public FindRequest() {
        }
        
        public FindRequest(ConsoleAppClient.ITPIService.BaseModel model, string[][] criteria) {
            this.model = model;
            this.criteria = criteria;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindResponse", WrapperNamespace="http://localhost:8888/Services/ITPI/Service1.asmx", IsWrapped=true)]
    public partial class FindResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost:8888/Services/ITPI/Service1.asmx", Order=0)]
        public string FindResult;
        
        public FindResponse() {
        }
        
        public FindResponse(string FindResult) {
            this.FindResult = FindResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : ConsoleAppClient.ITPIService.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<ConsoleAppClient.ITPIService.Service1Soap>, ConsoleAppClient.ITPIService.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Message(string request) {
            return base.Channel.Message(request);
        }
        
        public string GetPrInfo(ConsoleAppClient.ITPIService.PrEproc domain) {
            return base.Channel.GetPrInfo(domain);
        }
        
        public string GetPrLineInfo(ConsoleAppClient.ITPIService.PrLineEproc domain) {
            return base.Channel.GetPrLineInfo(domain);
        }
        
        public string GetPrSubtaskInfo(ConsoleAppClient.ITPIService.PrSubTask domain) {
            return base.Channel.GetPrSubtaskInfo(domain);
        }
        
        public string InsertDepartment(ConsoleAppClient.ITPIService.Department departemen) {
            return base.Channel.InsertDepartment(departemen);
        }
        
        public string InsertEmployee(ConsoleAppClient.ITPIService.Employee employee) {
            return base.Channel.InsertEmployee(employee);
        }
        
        public string InsertVendor(ConsoleAppClient.ITPIService.Vendor vendor) {
            return base.Channel.InsertVendor(vendor);
        }
        
        public string InsertCity(ConsoleAppClient.ITPIService.City city) {
            return base.Channel.InsertCity(city);
        }
        
        public string InsertProvince(ConsoleAppClient.ITPIService.Province prov) {
            return base.Channel.InsertProvince(prov);
        }
        
        public string InsertPR(ConsoleAppClient.ITPIService.PurchaseRequisition pr) {
            return base.Channel.InsertPR(pr);
        }
        
        public string InsertPrLine(ConsoleAppClient.ITPIService.PurchaseRequisitionLine prl) {
            return base.Channel.InsertPrLine(prl);
        }
        
        public string InsertPrDocument(ConsoleAppClient.ITPIService.PrDocument prDoc) {
            return base.Channel.InsertPrDocument(prDoc);
        }
        
        public string Get(ConsoleAppClient.ITPIService.BaseModel model) {
            return base.Channel.Get(model);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleAppClient.ITPIService.FindResponse ConsoleAppClient.ITPIService.Service1Soap.Find(ConsoleAppClient.ITPIService.FindRequest request) {
            return base.Channel.Find(request);
        }
        
        public string Find(ConsoleAppClient.ITPIService.BaseModel model, string[][] criteria) {
            ConsoleAppClient.ITPIService.FindRequest inValue = new ConsoleAppClient.ITPIService.FindRequest();
            inValue.model = model;
            inValue.criteria = criteria;
            ConsoleAppClient.ITPIService.FindResponse retVal = ((ConsoleAppClient.ITPIService.Service1Soap)(this)).Find(inValue);
            return retVal.FindResult;
        }
        
        public bool IsPrApproved(string prId) {
            return base.Channel.IsPrApproved(prId);
        }
        
        public string CreatePO(string jsonParameters) {
            return base.Channel.CreatePO(jsonParameters);
        }
    }
}
