//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://www.ibm.com/maximo/wsdl/EPROC_TPSCPOInterface", ConfigurationName="EPROC_TPSCPOInterfacePortType")]
public interface EPROC_TPSCPOInterfacePortType
{
    
    // CODEGEN: Generating message contract since the operation CreateTPSCPO is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute(Action="urn:processDocument", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    CreateTPSCPOResponse CreateTPSCPO(CreateTPSCPORequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:processDocument", ReplyAction="*")]
    System.Threading.Tasks.Task<CreateTPSCPOResponse> CreateTPSCPOAsync(CreateTPSCPORequest request);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ibm.com/maximo")]
public partial class CreateTPSCPOType
{
    
    private TPSCPO_POType[] tPSCPOSetField;
    
    private System.DateTime creationDateTimeField;
    
    private bool creationDateTimeFieldSpecified;
    
    private string baseLanguageField;
    
    private string transLanguageField;
    
    private string messageIDField;
    
    private string maximoVersionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
    [System.Xml.Serialization.XmlArrayItemAttribute("PO", IsNullable=false)]
    public TPSCPO_POType[] TPSCPOSet
    {
        get
        {
            return this.tPSCPOSetField;
        }
        set
        {
            this.tPSCPOSetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime creationDateTime
    {
        get
        {
            return this.creationDateTimeField;
        }
        set
        {
            this.creationDateTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool creationDateTimeSpecified
    {
        get
        {
            return this.creationDateTimeFieldSpecified;
        }
        set
        {
            this.creationDateTimeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string baseLanguage
    {
        get
        {
            return this.baseLanguageField;
        }
        set
        {
            this.baseLanguageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string transLanguage
    {
        get
        {
            return this.transLanguageField;
        }
        set
        {
            this.transLanguageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string messageID
    {
        get
        {
            return this.messageIDField;
        }
        set
        {
            this.messageIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string maximoVersion
    {
        get
        {
            return this.maximoVersionField;
        }
        set
        {
            this.maximoVersionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ibm.com/maximo")]
public partial class TPSCPO_POType
{
    
    private string mAXINTERRORMSGField;
    
    private MXStringType dEPARTMENTField;
    
    private MXStringType dESCRIPTIONField;
    
    private MXStringType pONUMField;
    
    private MXStringType pOSCOPEField;
    
    private MXStringType pURCHASEAGENTField;
    
    private MXLongType rEVISIONNUMField;
    
    private MXStringType sITEIDField;
    
    private MXStringType vENDORField;
    
    private TPSCPO_POLINEType[] pOLINEField;
    
    private ProcessingActionType actionField;
    
    private bool actionFieldSpecified;
    
    private string relationshipField;
    
    private string deleteForInsertField;
    
    private string transLanguageField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string MAXINTERRORMSG
    {
        get
        {
            return this.mAXINTERRORMSGField;
        }
        set
        {
            this.mAXINTERRORMSGField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public MXStringType DEPARTMENT
    {
        get
        {
            return this.dEPARTMENTField;
        }
        set
        {
            this.dEPARTMENTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public MXStringType DESCRIPTION
    {
        get
        {
            return this.dESCRIPTIONField;
        }
        set
        {
            this.dESCRIPTIONField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public MXStringType PONUM
    {
        get
        {
            return this.pONUMField;
        }
        set
        {
            this.pONUMField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public MXStringType POSCOPE
    {
        get
        {
            return this.pOSCOPEField;
        }
        set
        {
            this.pOSCOPEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=5)]
    public MXStringType PURCHASEAGENT
    {
        get
        {
            return this.pURCHASEAGENTField;
        }
        set
        {
            this.pURCHASEAGENTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
    public MXLongType REVISIONNUM
    {
        get
        {
            return this.rEVISIONNUMField;
        }
        set
        {
            this.rEVISIONNUMField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=7)]
    public MXStringType SITEID
    {
        get
        {
            return this.sITEIDField;
        }
        set
        {
            this.sITEIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=8)]
    public MXStringType VENDOR
    {
        get
        {
            return this.vENDORField;
        }
        set
        {
            this.vENDORField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("POLINE", Order=9)]
    public TPSCPO_POLINEType[] POLINE
    {
        get
        {
            return this.pOLINEField;
        }
        set
        {
            this.pOLINEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ProcessingActionType action
    {
        get
        {
            return this.actionField;
        }
        set
        {
            this.actionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool actionSpecified
    {
        get
        {
            return this.actionFieldSpecified;
        }
        set
        {
            this.actionFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string relationship
    {
        get
        {
            return this.relationshipField;
        }
        set
        {
            this.relationshipField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string deleteForInsert
    {
        get
        {
            return this.deleteForInsertField;
        }
        set
        {
            this.deleteForInsertField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string transLanguage
    {
        get
        {
            return this.transLanguageField;
        }
        set
        {
            this.transLanguageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ibm.com/maximo")]
public partial class MXStringType
{
    
    private bool changedField;
    
    private bool changedFieldSpecified;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool changed
    {
        get
        {
            return this.changedField;
        }
        set
        {
            this.changedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool changedSpecified
    {
        get
        {
            return this.changedFieldSpecified;
        }
        set
        {
            this.changedFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ibm.com/maximo")]
public partial class POKeyType
{
    
    private MXStringType sITEIDField;
    
    private MXStringType pONUMField;
    
    private MXLongType rEVISIONNUMField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public MXStringType SITEID
    {
        get
        {
            return this.sITEIDField;
        }
        set
        {
            this.sITEIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public MXStringType PONUM
    {
        get
        {
            return this.pONUMField;
        }
        set
        {
            this.pONUMField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
    public MXLongType REVISIONNUM
    {
        get
        {
            return this.rEVISIONNUMField;
        }
        set
        {
            this.rEVISIONNUMField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ibm.com/maximo")]
public partial class MXLongType
{
    
    private bool changedField;
    
    private bool changedFieldSpecified;
    
    private long valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool changed
    {
        get
        {
            return this.changedField;
        }
        set
        {
            this.changedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool changedSpecified
    {
        get
        {
            return this.changedFieldSpecified;
        }
        set
        {
            this.changedFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public long Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ibm.com/maximo")]
public partial class CreateTPSCPOResponseType
{
    
    private POKeyType[] pOMboKeySetField;
    
    private System.DateTime creationDateTimeField;
    
    private bool creationDateTimeFieldSpecified;
    
    private string baseLanguageField;
    
    private string transLanguageField;
    
    private string messageIDField;
    
    private string maximoVersionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
    [System.Xml.Serialization.XmlArrayItemAttribute("PO", IsNullable=false)]
    public POKeyType[] POMboKeySet
    {
        get
        {
            return this.pOMboKeySetField;
        }
        set
        {
            this.pOMboKeySetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime creationDateTime
    {
        get
        {
            return this.creationDateTimeField;
        }
        set
        {
            this.creationDateTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool creationDateTimeSpecified
    {
        get
        {
            return this.creationDateTimeFieldSpecified;
        }
        set
        {
            this.creationDateTimeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string baseLanguage
    {
        get
        {
            return this.baseLanguageField;
        }
        set
        {
            this.baseLanguageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string transLanguage
    {
        get
        {
            return this.transLanguageField;
        }
        set
        {
            this.transLanguageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string messageID
    {
        get
        {
            return this.messageIDField;
        }
        set
        {
            this.messageIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string maximoVersion
    {
        get
        {
            return this.maximoVersionField;
        }
        set
        {
            this.maximoVersionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ibm.com/maximo")]
public partial class MXDoubleType
{
    
    private bool changedField;
    
    private bool changedFieldSpecified;
    
    private double valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool changed
    {
        get
        {
            return this.changedField;
        }
        set
        {
            this.changedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool changedSpecified
    {
        get
        {
            return this.changedFieldSpecified;
        }
        set
        {
            this.changedFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public double Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ibm.com/maximo")]
public partial class TPSCPO_POLINEType
{
    
    private MXLongType pOLINENUMField;
    
    private MXLongType pRLINENUMField;
    
    private MXStringType pRNUMField;
    
    private MXStringType tOSITEIDField;
    
    private MXDoubleType uNITCOSTField;
    
    private ProcessingActionType actionField;
    
    private bool actionFieldSpecified;
    
    private string relationshipField;
    
    private string deleteForInsertField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
    public MXLongType POLINENUM
    {
        get
        {
            return this.pOLINENUMField;
        }
        set
        {
            this.pOLINENUMField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
    public MXLongType PRLINENUM
    {
        get
        {
            return this.pRLINENUMField;
        }
        set
        {
            this.pRLINENUMField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public MXStringType PRNUM
    {
        get
        {
            return this.pRNUMField;
        }
        set
        {
            this.pRNUMField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public MXStringType TOSITEID
    {
        get
        {
            return this.tOSITEIDField;
        }
        set
        {
            this.tOSITEIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
    public MXDoubleType UNITCOST
    {
        get
        {
            return this.uNITCOSTField;
        }
        set
        {
            this.uNITCOSTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ProcessingActionType action
    {
        get
        {
            return this.actionField;
        }
        set
        {
            this.actionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool actionSpecified
    {
        get
        {
            return this.actionFieldSpecified;
        }
        set
        {
            this.actionFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string relationship
    {
        get
        {
            return this.relationshipField;
        }
        set
        {
            this.relationshipField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string deleteForInsert
    {
        get
        {
            return this.deleteForInsertField;
        }
        set
        {
            this.deleteForInsertField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ibm.com/maximo")]
public enum ProcessingActionType
{
    
    /// <remarks/>
    Add,
    
    /// <remarks/>
    Change,
    
    /// <remarks/>
    Replace,
    
    /// <remarks/>
    Delete,
    
    /// <remarks/>
    AddChange,
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class CreateTPSCPORequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ibm.com/maximo", Order=0)]
    public CreateTPSCPOType CreateTPSCPO;
    
    public CreateTPSCPORequest()
    {
    }
    
    public CreateTPSCPORequest(CreateTPSCPOType CreateTPSCPO)
    {
        this.CreateTPSCPO = CreateTPSCPO;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class CreateTPSCPOResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateTPSCPOResponse", Namespace="http://www.ibm.com/maximo", Order=0)]
    public CreateTPSCPOResponseType CreateTPSCPOResponse1;
    
    public CreateTPSCPOResponse()
    {
    }
    
    public CreateTPSCPOResponse(CreateTPSCPOResponseType CreateTPSCPOResponse1)
    {
        this.CreateTPSCPOResponse1 = CreateTPSCPOResponse1;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface EPROC_TPSCPOInterfacePortTypeChannel : EPROC_TPSCPOInterfacePortType, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class EPROC_TPSCPOInterfacePortTypeClient : System.ServiceModel.ClientBase<EPROC_TPSCPOInterfacePortType>, EPROC_TPSCPOInterfacePortType
{
    
    public EPROC_TPSCPOInterfacePortTypeClient()
    {
    }
    
    public EPROC_TPSCPOInterfacePortTypeClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public EPROC_TPSCPOInterfacePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public EPROC_TPSCPOInterfacePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public EPROC_TPSCPOInterfacePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    CreateTPSCPOResponse EPROC_TPSCPOInterfacePortType.CreateTPSCPO(CreateTPSCPORequest request)
    {
        return base.Channel.CreateTPSCPO(request);
    }
    
    public CreateTPSCPOResponseType CreateTPSCPO(CreateTPSCPOType CreateTPSCPO1)
    {
        CreateTPSCPORequest inValue = new CreateTPSCPORequest();
        inValue.CreateTPSCPO = CreateTPSCPO1;
        CreateTPSCPOResponse retVal = ((EPROC_TPSCPOInterfacePortType)(this)).CreateTPSCPO(inValue);
        return retVal.CreateTPSCPOResponse1;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<CreateTPSCPOResponse> EPROC_TPSCPOInterfacePortType.CreateTPSCPOAsync(CreateTPSCPORequest request)
    {
        return base.Channel.CreateTPSCPOAsync(request);
    }
    
    public System.Threading.Tasks.Task<CreateTPSCPOResponse> CreateTPSCPOAsync(CreateTPSCPOType CreateTPSCPO)
    {
        CreateTPSCPORequest inValue = new CreateTPSCPORequest();
        inValue.CreateTPSCPO = CreateTPSCPO;
        return ((EPROC_TPSCPOInterfacePortType)(this)).CreateTPSCPOAsync(inValue);
    }
}
