SET FOREIGN_KEY_CHECKS = 0; 
TRUNCATE `log_activity`;
ALTER TABLE `log_activity`	AUTO_INCREMENT=1;
TRUNCATE `bpm`;
ALTER TABLE `bpm`	AUTO_INCREMENT=1;
TRUNCATE `detail_analisa_rab`;
ALTER TABLE `detail_analisa_rab`	AUTO_INCREMENT=1;
TRUNCATE `detail_bpm`;
ALTER TABLE `detail_bpm`	AUTO_INCREMENT=1;
TRUNCATE `detail_hm`;
ALTER TABLE `detail_hm`	AUTO_INCREMENT=1;
TRUNCATE `detail_invoice`;
ALTER TABLE `detail_invoice`	AUTO_INCREMENT=1;
TRUNCATE `detail_km`;
ALTER TABLE `detail_km`	AUTO_INCREMENT=1;
TRUNCATE `detail_lpb`;
ALTER TABLE `detail_lpb`	AUTO_INCREMENT=1;
TRUNCATE `detail_lpu`;
ALTER TABLE `detail_lpu`	AUTO_INCREMENT=1;
TRUNCATE `detail_overhead`;
ALTER TABLE `detail_overhead`	AUTO_INCREMENT=1;
TRUNCATE `detail_pekerjaan`;
ALTER TABLE `detail_pekerjaan`	AUTO_INCREMENT=1;
TRUNCATE `detail_po`;
ALTER TABLE `detail_po`	AUTO_INCREMENT=1;
TRUNCATE `detail_pm`;
ALTER TABLE `detail_pm`	AUTO_INCREMENT=1;
TRUNCATE `detail_transaksi_opname`;
ALTER TABLE `detail_transaksi_opname`	AUTO_INCREMENT=1;
TRUNCATE `detail_transaksi_pk`;
ALTER TABLE `detail_transaksi_pk`	AUTO_INCREMENT=1;
TRUNCATE `detail_transaksi_pp`;
ALTER TABLE `detail_transaksi_pp`	AUTO_INCREMENT=1;
TRUNCATE `enroll`;
ALTER TABLE `enroll`	AUTO_INCREMENT=1;
TRUNCATE `gudangxbarang`;
ALTER TABLE `gudangxbarang`	AUTO_INCREMENT=1;
TRUNCATE `hutang_barang`;
ALTER TABLE `hutang_barang`	AUTO_INCREMENT=1;
TRUNCATE `invoice`;
ALTER TABLE `invoice`	AUTO_INCREMENT=1;
TRUNCATE `kembali_barang`;
ALTER TABLE `kembali_barang`	AUTO_INCREMENT=1;
TRUNCATE `lpu`;
ALTER TABLE `lpu`	AUTO_INCREMENT=1;
TRUNCATE `main_project`;
ALTER TABLE `main_project`	AUTO_INCREMENT=1;
TRUNCATE `master_gudang`;
ALTER TABLE `master_gudang`	AUTO_INCREMENT=1;
TRUNCATE `master_supplier`;
ALTER TABLE `master_supplier`	AUTO_INCREMENT=1;
TRUNCATE `notifications`;
ALTER TABLE `notifications`	AUTO_INCREMENT=1;
TRUNCATE `notifxpengguna`;
ALTER TABLE `notifxpengguna`	AUTO_INCREMENT=1;
TRUNCATE `opname`;
ALTER TABLE `opname`	AUTO_INCREMENT=1;
TRUNCATE `overhead`;
ALTER TABLE `overhead`	AUTO_INCREMENT=1;
TRUNCATE `paket_overhead_material`;
ALTER TABLE `paket_overhead_material`	AUTO_INCREMENT=1;
TRUNCATE `paket_overhead_upah`;
ALTER TABLE `paket_overhead_upah`	AUTO_INCREMENT=1;	
TRUNCATE `payment`;
ALTER TABLE `payment`	AUTO_INCREMENT=1;	
TRUNCATE `penerimaan_barang`;
ALTER TABLE `penerimaan_barang`	AUTO_INCREMENT=1;	
TRUNCATE `permintaan_pekerjaan`;
ALTER TABLE `permintaan_pekerjaan`	AUTO_INCREMENT=1;	
TRUNCATE `permintaan_pembelian`;
ALTER TABLE `permintaan_pembelian`	AUTO_INCREMENT=1;	
TRUNCATE `perusahaan`;
ALTER TABLE `perusahaan`	AUTO_INCREMENT=1;	
TRUNCATE `poxlpb`;
ALTER TABLE `poxlpb`	AUTO_INCREMENT=1;	
TRUNCATE `project`;
ALTER TABLE `project`	AUTO_INCREMENT=1;	
TRUNCATE `rab_transaction`;
ALTER TABLE `rab_transaction`	AUTO_INCREMENT=1;	
TRUNCATE `stok`;
ALTER TABLE `stok`	AUTO_INCREMENT=1;	
TRUNCATE `subcon`;
ALTER TABLE `subcon`	AUTO_INCREMENT=1;	



SET FOREIGN_KEY_CHECKS = 1;